# Generated by Django 5.1.2 on 2025-10-31 21:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the food item', null=True, upload_to=core.models.donation_image_path),
        ),
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=models.TextField(help_text='A brief description of the food item'),
        ),
    ]
