# Generated by Django 5.1.2 on 2025-11-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donation_image_alter_donation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='image',
        ),
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=models.TextField(),
        ),
    ]
