# Generated by Django 5.1.2 on 2025-11-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_donation_latitude_donation_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='longitude',
        ),
    ]
